steps:
- id: Docker-build-push
  name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args:
  - -c
  - |-
    docker build -t test .
    docker push test
- id: google-cloud-run
  name: gcr.io/cloud-builders/gcloud
  entrypoint: sh
  args:
  - -c
  - |-
    gcloud run services update pigen-demo \
    --region=us-east1 \
    --image=us-east1-docker.pkg.dev/${PROJECT_ID}/butly-bot-images/app:${SHORT_SHA} \
      --set-secrets=MY_SECRET=PIGEN_MY_SECRET:latest \
options:
  logging: CLOUD_LOGGING_ONLY
